#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidAboutPage.Resource", IsApplication=false)]

namespace AndroidAboutPage
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public static int about_description_color = 2130968583;
			
			// aapt resource value: 0x7f040006
			public static int about_item_icon_color = 2130968582;
			
			// aapt resource value: 0x7f040009
			public static int about_item_text_color = 2130968585;
			
			// aapt resource value: 0x7f040008
			public static int about_separator_color = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public static int about_text_color = 2130968586;
			
			// aapt resource value: 0x7f040000
			public static int facebook_color = 2130968576;
			
			// aapt resource value: 0x7f040005
			public static int github_color = 2130968581;
			
			// aapt resource value: 0x7f040002
			public static int instagram_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int play_store_color = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int twitter_color = 2130968577;
			
			// aapt resource value: 0x7f040004
			public static int youtube_color = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050005
			public static int about_description_text_size = 2131034117;
			
			// aapt resource value: 0x7f050007
			public static int about_group_item_text_size = 2131034119;
			
			// aapt resource value: 0x7f050003
			public static int about_group_text_padding = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int about_icon_padding = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int about_icon_size = 2131034112;
			
			// aapt resource value: 0x7f050006
			public static int about_item_text_size = 2131034118;
			
			// aapt resource value: 0x7f050004
			public static int about_separator_height = 2131034116;
			
			// aapt resource value: 0x7f050002
			public static int about_text_padding = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int about_icon_email = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int about_icon_facebook = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int about_icon_github = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int about_icon_google_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int about_icon_instagram = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int about_icon_link = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int about_icon_twitter = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int about_icon_youtube = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public static int about_providers = 2131230722;
			
			// aapt resource value: 0x7f080001
			public static int description = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int image = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int about_page = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int about_page_separator = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public static int about_contact_us = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int about_facebook = 2131099651;
			
			// aapt resource value: 0x7f060007
			public static int about_github = 2131099655;
			
			// aapt resource value: 0x7f060002
			public static int about_instagram = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int about_page_description = 2131099648;
			
			// aapt resource value: 0x7f060004
			public static int about_play_store = 2131099652;
			
			// aapt resource value: 0x7f060006
			public static int about_twitter = 2131099654;
			
			// aapt resource value: 0x7f060008
			public static int about_website = 2131099656;
			
			// aapt resource value: 0x7f060005
			public static int about_youtube = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int About = 2131165184;
			
			// aapt resource value: 0x7f070007
			public static int About_GroupTextAppearance = 2131165191;
			
			// aapt resource value: 0x7f070004
			public static int About_description = 2131165188;
			
			// aapt resource value: 0x7f070006
			public static int About_elementTextAppearance = 2131165190;
			
			// aapt resource value: 0x7f070003
			public static int About_image = 2131165187;
			
			// aapt resource value: 0x7f070005
			public static int About_separator = 2131165189;
			
			// aapt resource value: 0x7f070002
			public static int About_sub_wrapper = 2131165186;
			
			// aapt resource value: 0x7f070001
			public static int About_wrapper = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
